

 function plot_coast

names = { ...
'costa_sul' , ...
'costa_floripa' , ...
'costa_guaiba' , ...
'costa_ilha_bela', ...
'costa_ilha_campeche' , ...
'costa_ilha_cananeia' , ...
'costa_ilha_cardoso' , ...
'costa_ilha_comprida' , ...
'costa_ilha_das_pecas_google' , ...
'costa_ilha_do_mel' , ...
'costa_ilha_fundao' , ...
'costa_ilha_grande' , ...
'costa_paranagua_ilha_da_cotinga' , ...
'costa_paranagua_ilha_das_pecas' , ...
'costa_paranagua_ilha_do_povoca' , ...
'costa_paranagua_ilha_do_rabelo' , ...
'costa_paranagua_ilha_dos_valadares' , ...
'costa_paranagua_ilha_mariana' , ...
'costa_paranagua_ilha_rasa_da_cotinga' , ...
'costa_paranagua_ilha_rasa' , ...
'costa_restinga_marambaia' , ...
'costa_sao_chico'  ...
    };

addpath '~/data/costas'

for n =1:length(names)
    load(names{n})
    fill(lon,lat,[.3 .7 .2])
    hold on
end
